//POST ACTIONS

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const GET_POSTS_BY_SEARCH_REQUEST = "GET_POSTS_BY_SEARCH_REQUEST";
export const GET_POSTS_BY_SEARCH_SUCCESS = "GET_POSTS_BY_SEARCH_SUCCESS";
export const GET_POSTS_BY_SEARCH_FAILURE = "GET_POSTS_BY_SEARCH_FAILURE";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export const DELETE_POST = "DELETE_POST";

export const COMMENT_POST_REQUEST = "COMMENT_POST_REQUEST ";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE";

export const GET_USER_POSTS_REQUEST = "GET_USER_POSTS_REQUEST";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_FAILURE = "GET_USER_POSTS_FAILURE";

// AUTH ACTIONS

export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_SUCCESS = "AUTH_SECCESS";

export const LOGOUT = "LOGOUT";
